name: Build and push docker image

inputs:
  repository:
    description: '<org>/<repo> Repository that contains the Dockerfile to build'
    required: true
    type: string
  directory:
    description: 'Directory that contains the Dockerfile to build'
    required: true
    type: string
  image_name:
    description: '<org>/<image-name> Name of the image to deploy'
    required: true
    type: string
  docker_registry:
    description: 'Docker registry to push to'
    required: true
    default: 'ghcr.io'
    type: string
  github_ref_before:
    description: 'Github ref before the change'
    required: true
    type: string
  github_ref_after:
    description: 'Github ref after the change'
    required: true
    type: string
  github_token:
    description: 'Github token'
    required: true
    type: string
  github_user:
    description: 'Github user'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout Dockerfile
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        path: dockerfile-repo
        ref: ${{ inputs.github_ref_after }}
        token: ${{ inputs.github_token }}
        fetch-depth: 0
    - name: Check for changes
      id: check-for-changes
      run: |
        changed_files=$(git diff --name-only ${{ inputs.github_ref_before }} ${{ inputs.github_ref_after }} | grep "^${{ inputs.directory }}" | wc  -l)"
        is_changed=true
        if [ $changed_files -eq 0 ]; then
          is_changed=false
        fi
        echo "is_changed=$is_changed" >> $GITHUB_ENV
      working-directory: dockerfile-repo
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.docker_registry }}/${{ inputs.image_name }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.github_user }}
        password: ${{ inputs.github_token }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.directory }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache-from: type=gha
        cache-to: type=gha,mode=max
