name: 'Download assets from GitHub release'
description: 'Greet someone'
inputs:
  owner:
    description: 'Owner of the repo'
    required: true
  repo:
    description: 'Repo name'
    required: true
  release-tag:
    description: 'Release tag'
    required: true
  regex:
    description: 'Regex to match assets'
    required: true
  dest-dir:
    description: 'Destination directory'
    required: true
outputs:
  out-dir:
    description: 'Output directory'
    value: ${{ inputs.dest-dir }}
runs:
  using: "composite"
  steps:
    - name: Download release info
      env:
        RELEASE_JSON_PATH: release.json
      id: download-release-info
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -o ${RELEASE_JSON_PATH} \
        https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/releases/tags/${{ inputs.release-tag }}
        echo "release-id=$(cat ${RELEASE_JSON_PATH} | jq -r '.id')" >> $GITHUB_OUTPUT
      shell: bash
    - name: Download assets list
      env:
        ASSETS_JSON_PATH: assets.json
      id: download-assets-list
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -o ${ASSETS_JSON_PATH} \
        https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/releases/${{ steps.download-release-info.outputs.release-id }}/assets
        echo "assets-json-path=${ASSETS_JSON_PATH}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Create download list
      id: create-download-list
      shell: bash
      env:
        DOWNLOAD_LIST_PATH: download-list.txt
      run: |
        cat ${{ steps.download-assets-list.outputs.assets-json-path }} | jq -r --arg regex "${{ inputs.regex }}" '.[] | select(.name | test($regex)) | .browser_download_url' > ${DOWNLOAD_LIST_PATH}
        echo "download-list-path=${DOWNLOAD_LIST_PATH}" >> $GITHUB_OUTPUT
    - name: Download assets
      id: download-assets
      shell: bash
      run: |
        cat ${{ steps.create-download-list.outputs.download-list-path }} | xargs -n 1 curl -L -O
      working-directory: ${{ inputs.dest-dir }}
