name: Build and push docker images hosted on everest-ci

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build-and-push-all-images:
    name: Build and push all docker images
    strategy:
      matrix:
        include: 
          - image_name: andistorm/everest-clang-format
            directory: docker/everest-clang-format
    runs-on: ubuntu-22.04
    steps:
      - name: Build and Deploy Docker Image
        # LTODO andistorm -> everest
        uses: andistorm/everest-ci/github-actions/build-and-deploy-docker-image@andistorm-clang-format
        with:
          repository: andistorm/everest-ci
          directory: ${{ matrix.directory }}
          image_name: ${{ matrix.image_name }}
          docker_registry: ${{ env.CONTAINER_REGISTRY }}
          github_ref_before: ${{ github.event.before }}
          github_ref_after: ${{ github.event.after }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user: ${{ github.actor }}
