name: Build and push docker images hosted on everest-ci

on:
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if no changes are detected'
        required: false
        type: boolean
  push:
    branches:
      - '**'
    tags:
      - 'v*'

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build-and-push-all-images:
    name: Build and push all docker images
    strategy:
      matrix:
        include: 
          - image_name: everest/everest-clang-format
            directory: docker/images/everest-clang-format
          - image_name: everest/build-kit-alpine
            directory: docker/images/build-kit
            file: alpine.Dockerfile
          - image_name: everest/build-kit-debian
            directory: docker/images/build-kit
            file: debian.Dockerfile
    runs-on: ubuntu-22.04
    steps:
      - name: Build and Deploy Docker Image
        uses: everest/everest-ci/github-actions/build-and-deploy-docker-image@v1.1.0
        with:
          repository: everest/everest-ci
          directory: ${{ matrix.directory }}
          image_name: ${{ matrix.image_name }}
          dockerfile: ${{ matrix.file || 'Dockerfile' }}
          docker_registry: ${{ env.CONTAINER_REGISTRY }}
          github_ref_before: ${{ github.event.before }}
          github_ref_after: ${{ github.event.after }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user: ${{ github.actor }}
          force_build: ${{ inputs.force_build || false }}
